@url = "http://localhost:5000"

### adding user
POST  http://localhost:5000/api HTTP/1.1
Content-Type: application/json

{
    "name":" pomaa"
}


#### getting user
GET  http://localhost:5000/api/64ff75c0b5dd336d29ebc3cf HTTP/1.1

### updating user
PUT  http://localhost:5000/api/64ff75c0b5dd336d29ebc3cf HTTP/1.1
Content-Type: application/json

{
     "name":"Pomaa"
}

### deleting user
DELETE http://localhost:5000/api/64ff4755260f0330c69703ce HTTP/1.1


### getting all users
GET http://localhost:5000/api HTTP/1.1


####
https://userdetails-k0rw.onrender.com